import type { CollectionSchema } from 'deepspace/schema'

/**
 * One trip = one boat out. `expectedReturnAt` and `departedAt` are UTC
 * ISO-8601 strings (see src/lib/time.ts) — the overdue cron compares them
 * directly against `Date.now()`, no timezone math needed server-side.
 *
 * Any signed-in shore watch member can create, update (log a departure,
 * check a boat in), and read every trip — this is a shared team board, not
 * a personal log, so there is no 'own'-scoped permission here. Only an
 * admin (the dock lead) can delete, so the event timeline stays intact.
 */
export const tripsSchema: CollectionSchema = {
  name: 'trips',
  columns: [
    { name: 'vesselName', storage: 'text', interpretation: 'plain', required: true },
    { name: 'vesselDescription', storage: 'text', interpretation: 'plain', default: '' },
    { name: 'skipper', storage: 'text', interpretation: 'plain', required: true },
    { name: 'personsAboard', storage: 'number', interpretation: 'plain', required: true, default: 1 },
    { name: 'plannedArea', storage: 'text', interpretation: 'plain', default: '' },
    { name: 'departedAt', storage: 'text', interpretation: { kind: 'datetime' }, required: true },
    { name: 'expectedReturnAt', storage: 'text', interpretation: { kind: 'datetime' }, required: true },
    {
      name: 'status',
      storage: 'text',
      interpretation: { kind: 'select', options: ['out', 'overdue', 'returned'] },
      required: true,
      default: 'out',
    },
    { name: 'checkedInAt', storage: 'text', interpretation: { kind: 'datetime' } },
    { name: 'alertSentAt', storage: 'text', interpretation: { kind: 'datetime' } },
    { name: 'alertCount', storage: 'number', interpretation: 'plain', default: 0 },
    // Generated by the M3 call-sheet job; JSON so partial/missing-info
    // shape (script, missingInfo, generatedAt, source) travels as one value.
    { name: 'callSheet', storage: 'text', interpretation: { kind: 'json' } },
    { name: 'isSample', storage: 'number', interpretation: { kind: 'boolean' }, default: 0 },
  ],
  permissions: {
    viewer: { read: false, create: false, update: false, delete: false },
    member: { read: true, create: true, update: true, delete: false },
    admin: { read: true, create: true, update: true, delete: true },
  },
}
